### ISSUE TITLE
Новая фуникцональность

### ISSUE THREAD

**Issue by noveogroup-amorgunov** [aslepenkov/yandex-js-dashboard#3]
- красить ячейку в желтый цвет, если задача решена после дедлайна
- вместо 1345, 5746 показывать 1.3к, 5.7к

И можно подумать на счет того, что бы время старта задач брать день выдачи, потому что sebay решил задачу Pi-approximation, и у всех до +5к часов разницы

**Comment by aslepenkov** [comment]
Обновил, выкатил!
 
- [x] красить ячейку в желтый цвет, если задача решена после дедлайна
- [x] вместо 1345, 5746 показывать 1.3к, 5.7к
- [x] diff time не может быть больше, чем до даты старта задачи
- [x] размер шрифта мельче
